# Generated by Django 5.0.6 on 2024-05-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('image', models.CharField(max_length=600)),
            ],
        ),
    ]
