# Generated by Django 5.0.6 on 2024-06-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_offerproducts_alter_brands_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('product_details', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
